region: ${AWS_DEFAULT_REGION}
cluster: grdev-front_api-cluster
service: grdev-front_api-new_igen
service_definition: ecs-service-def.json
task_definition: ecs-task-def.json
timeout: 12m0s
plugins: []
appspec: null
